### PR TITLE
Add action to start event from dropdown

### PR DESCRIPTION
**Pull request by markspolakovs**
Currently your choices for starting an event are either by index (which is unpredictable if things are moved around) or by ID (which requires finding the ID which isn't user friendly).

This PR adds an action that works the same way as "Start event with given ID", but has a dropdown picker of all events known to the OnTime instance.

### CODE REVIEW

**Comment by kellhogs** [comment]
hey @markspolakovs, this looks like a great addidtion to the module.
We are currently in the process of getting PR #9 merged, wich makes the module Companion V3 compatible. 
This also restructures the way actions are called. 

I think you should take a look at the PR #9 and adapt your code to these changes, so we can merge without any trouble.

Also as far as i have seen you only pull the event's in, at the initialisation of the module. The problem with that would be, that if the user adds or removes events after companion is started he would not get any updates without restarting companion.
Maybe @cpvalente has some thoughts on how to resolve this issue, beeing that V2 of ontime is almost in the beta phase

**Comment by markspolakovs** [comment]
@kellhogs 

> hey @markspolakovs, this looks like a great addidtion to the module. We are currently in the process of getting PR #9 merged, wich makes the module Companion V3 compatible. This also restructures the way actions are called.
> 
> I think you should take a look at the PR #9 and adapt your code to these changes, so we can merge without any trouble.

Can do, though I'm still using v2 while v3 is in beta, so in a perfect world I'd like to get this into both - is there a process for having two versions available in parallel? If not I'm happy to adapt this to v3 and maintain a v2 version myself.

> Also as far as i have seen you only pull the event's in, at the initialisation of the module. The problem with that would be, that if the user adds or removes events after companion is started he would not get any updates without restarting companion. Maybe @cpvalente has some thoughts on how to resolve this issue, beeing that V2 of ontime is almost in the beta phase

Yeah, that is an issue - I've worked around it by also pulling them in when the module settings are updated (`updateConfig`), so the user can go to the connections page, hit Update, and Save to force it to refresh - it's what modules like https://github.com/bitfocus/companion-module-casparcg-server do, unless you know of a better way of doing this?

**Comment by kellhogs** [comment]
Correct me if im wrong @Julusian, but as far as i know companion V2 wont get any updates feature updates until V3 get released next year and i dont know if modules get updated in bug fix updates. 
Anyway the code looks good to me and if we can get it into a V2 update im happy to have it merged. 
Unfortunately i cant do that in this repository.

**Comment by markspolakovs** [comment]
@kellhogs I've opened https://github.com/kellhogs/companion-module-getontime-ontime/pull/3 as a V3 version - I opened it against the V3 branch in your fork so that the diff would be cleaner, but I should be able to change it to point to this repo once that's merged.

**Comment by Julusian** [comment]
Yes the intention is that 2.x wont be getting any more module updates

**Comment by markspolakovs** [comment]
Makes sense, I'm happy to close this in favour of #11 then.

**Comment by cpvalente** [comment]
Hey, this is an excellent quality-of-life addition to the module. Thank you very much for your work.
As you mentioned, let's close this one in favour of #11. We would need to merge the migration in #9 first though

I will address the fetch in the PR to be merged

**Pull request closed without merging**
